### ISSUE TITLE
box display issues in Safari

### ISSUE THREAD

**Issue by TomHardwicke** [langcog/experimentology#108]
Boxes are looking weird in the Safari browser (see screenshots below). They look fine in Chrome.

![Screenshot 2023-01-23 at 12 31 13](https://user-images.githubusercontent.com/5615147/213952473-64e6e580-9557-4c59-a217-6a45a38bf22c.png)

![Screenshot 2023-01-23 at 12 31 36](https://user-images.githubusercontent.com/5615147/213952481-c51d493f-826f-4ded-a753-4565184e5ef7.png)

┆Issue is synchronized with this [Trello card](https://trello.com/c/Bmf9aVpD) by [Unito](https://www.unito.io)

**Comment by mikabr** [comment]
as of safari 16.4.1, boxes are the correct width, but latex rendering inside them is broken
