### ISSUE TITLE
table labels not aligned with tables

### ISSUE THREAD

**Issue by TomHardwicke** [langcog/experimentology#111]
Table labels and captions, which appear in the side bar, are not always aligned with their respective tables, which appear in the main body. I think it's because other content in the side bar is pushing the labels down the page. I've seen the problem in Safari and Chrome browsers. Two example tables:

Table 8.1 in [measurement](https://experimentology.io/8-measurement)

Table 6.1 in [inference](https://experimentology.io/6-inference)

┆Issue is synchronized with this [Trello card](https://trello.com/c/Cj9mFITY) by [Unito](https://www.unito.io)

**Comment by mikabr** [comment]
This isn't really a bug – the content is being put in the correct order, there's just a lot of figures before the table. I'm not sure what a solution would be other than manually playing around with figure sizing / placement?

**Comment by TomHardwicke** [comment]
can we put the table/figure captions in the main body rather than the sidebar?

**Comment by mikabr** [comment]
we could do that globally for all captions, but not only for some specific captions. it seems like a big change to make globally for the sake of just a few captions? but I'm open to it if there's general agreement about it.

**Comment by TomHardwicke** [comment]
is there a downside to having captions in the main body next to their corresponding figures/tables? If not I say we go for it - any thoughts @mcfrank ?

**Comment by mcfrank** [comment]
I think we want to sort out our float alignment problems by distributing sidenotes and by setting some tex penalties rather than by hard coding captions.
