### ISSUE TITLE
create printable book version

### ISSUE THREAD

**Issue by mikabr** [langcog/experimentology#116]
┆Issue is synchronized with this [Trello card](https://trello.com/c/vJRsDIdN) by [Unito](https://www.unito.io)

**Comment by TomHardwicke** [comment]
hey @mikabr we got [a question](https://scicomm.xyz/@nicebread/110252533441759399) asking if its possible to render the book as a pdf which I guess is linked to this issue. Is this planned for the future but not possible at the moment?

**Comment by mikabr** [comment]
Yes, the plan is to have the book render to a pdf that uses the MIT Press template/styling for publishing. Does that seem like it would address this use case?

**Comment by mikabr** [comment]
sometime over the next couple months, at the latest by the start of July
