### ISSUE TITLE
Small typo in section 13.1 "Principles of project management"

### ISSUE THREAD

**Issue by katashannon** [langcog/experimentology#117]
Extra "s" in preprocessing filename caught my eye in bullet item 2 in Section 13.1 "Principles of project management" -

The location of each document should be within a folder which serves to uniquely identify the document’s function within the project. For example, /analysis/experiment1/eye_tracking_**preprocesssing**.Rmd is clearly the file that performs pre-processing for the analysis of eye-tracking data from Experiment 1.

Thanks!

**Comment by TomHardwicke** [comment]
fixed, thank you @katashannon !

**Comment by TomHardwicke** [comment]
fixed, thank you @katashannon !
