### ISSUE TITLE
consistency in made up researcher examples

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#12]
In several chapters there are examples in which we might want to give fake citations or names, e.g. "don't say 'smith did something bad,' say 'there is an error in Smith and Jones (2018)'" - I find these examples useful but feel uncomfortable about any naming convention... smith and jones is much more innocuous than more gendered examples that are out there in the literature, but still these two are probably americans etc. Any thoughts?

**Comment by JMankewitz** [comment]
You could give a nod to obviously fictional characters like "Holmes and Watson (2018)" instead?

**Comment by kachergis** [comment]
Hark & Mistakerson?

**Comment by TomHardwicke** [comment]
Pikachu, Bulbasaur, & Magikarp (2021)
