### ISSUE TITLE
Chapter 3 feedback

### ISSUE THREAD

**Issue by ColesNicholas** [langcog/experimentology#124]
Great chapter. Few minor issues I noticed:

- The phrasing in Footnote 3 seemed odd to me. Maybe say “One of the authors of this textbook was a student in the course that year!”

- There is a typo in this sentence, which can be corrected by adding the following bolded letter: "The others yielded smaller effects that were no**t** significant in the replication sample.

- The following citation is rendering in a way that's listing Nosek's full name. I suspect that the other references list the name slightly differently, which could be why it's rendering differently. “Furthermore, the replication effect will be on average 53% as large (**Brian A.** Nosek et al., 2021).”

- In the analytic flexibility accident report, the Beatle’s song is not written correctly. It should say “When I'm **Sixty-Four**”. 64 is not written out as a number in the song title.

- This claim seems like an oversimplification: “The open science movement is a response – really a set of responses – to the challenges of reproducibility and replicability.” There was an open science movement pre-replication crisis, and the open science movement existed in disciplines that haven't grappled with a substantial replication crisis. I recommend you change to "he open science movement is, **in part**, a set of responses to the challenges..."

This in-text reference for the umbrella figure is not rendering properly: Here's what it looked like when I reviewed the chapter “…broader open scholarship) movement is a broad umbrella **(Figure @(fig:replication-umbrella))**”

Overall: great work!

**Comment by mcfrank** [comment]
thanks for the feedback, corrected these
