### ISSUE TITLE
adoption barriers

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#13]
worth thinking about where adoption barriers could be discussed, cf. https://doi.org/10.1525/collabra.18684

**Comment by TomHardwicke** [comment]
A few options:

1. If there are potential adoption barriers throughout the book then we could have "Adoption barrier" boxes akin to our "Accident report" boxes
2. If adoption barriers are only relevant to a few chapters then could just have dedicated boxes in these specific chapters, or a general "adoption barriers" appendix if issues span chapters (e.g., "my supervisor hates open science")
3. If adoption barriers only relevant to a few specific practices then could just address in sidebar wherever relevant

Perhaps we will find out which is best as we write. I'd be in favour of trying (1) and we can cut down to (2) or (3) if its not working.

**Comment by mcfrank** [comment]
I think I lean against it at the moment, but maybe that's because I'm
slightly in "ship it" mode (not adding more features). Would you be ok with
that?

**Comment by TomHardwicke** [comment]
yes I think that's fine

**Comment by mcfrank** [comment]
ok, closing this for now. thanks!
