### ISSUE TITLE
comments on chapter 1 — experiments

### ISSUE THREAD

**Issue by TomHardwicke** [langcog/experimentology#131]
I'm working through the book sequentially and these are my comments on chapter 1. I've also made some direct edits to the text for more minor things and writing adjustments and issued a [pull request](https://github.com/langcog/experimentology/pull/133).

- "The purpose of experiments is to estimate the magnitude of causal effects". This seems to narrow — what about testing hypotheses?
- Sidebar note 2: "People sometimes ask whether causation implies correlation (the opposite direction). The short answer is “also no.”" And then we provide an example of a car driving uphill and say that pressure on the gas pedal is no longer correlated with speed. Are we sure that's correct? They would still be correlated wouldn't they, it just wouldn't be a linear relationship? The accepted answer [here](https://stats.stackexchange.com/questions/26300/does-causation-imply-correlation) seems to imply that this is the case more generally i.e., that causation does not necessarily imply _linear_ correlation, but it does imply some kind of mutual dependence e.g., a non-linear relationship?
- In section 1.1 we discuss the difficulties of drawing causal conclusions from observational studies and then briefly mention that its possible if we use sophisticated methods that we're not going to talk about, which somewhat ruins the segue into section 1.2 on why experiments are so important! Perhaps we should say something general about the limitations of these methods to avoid implying they are magical and clarifying the rationale for doing experiments?
- Figure 1.4 text says "randomisation removes all unknown confounds" - but it also removes all known confounds so remove 'unknown'? (perhaps we should make a broader point in the main text that randomisation is particularly powerful because it removes the impact of confounds we're not even aware of).
- "When you randomize, you guarantee that on average all confounds are controlled and hence these do not bias your estimate." — this is a bit abrupt and it's not obvious how to reconcile with "[randomization] doesn’t work every time". More elaboration needed? Also I imagine a reader might think, why don't we just check to see if there is unhappy randomisation in each case and discard the studies where it 'didn't work' — so we might want to head that off.
- "Maybe we need to give a small amount of money to control participants to match the interactions with an experimenter between conditions." Maybe just me, but it might be worth unpacking this a bit for a naive reader (they might not know about experimenter effects).
- "do not generalize to people in South Korea" should perhaps be "may not generalize to people in South Korea" or "did not generalise to the South Korean sample" (because we don't know if the results generalise to all people in South Korea or not based on this one study).
- "do we mean that there is a linear increase?" — will readers know what means? We could add something like "...linear increase (an increase in one variable is matched by an equal increase in another variable) or is the relationship more complicated (for example, the two variables increase synchronously at an equal rate, but only up until a certain point)". But perhaps that's getting a bit complex for a summary section.

**Comment by mcfrank** [comment]
great comments. tried to address them!

re correlation/causation: I don't think linearity is critical here. the issue is that if there is an equal and opposite causal force, then you can have zero mutual information (and zero correlation). there's some discussion in the comments on the answer you linked.
