### ISSUE TITLE
comments on chapter 7 -- models

### ISSUE THREAD

**Issue by hawkrobe** [langcog/experimentology#134]
* 'estimating particular **parameters** of interest from empirical data [...] -- and making inferences about their relationship to the population parameter(s).' 
  * I wasn't sure what the end of this sentence meant, as the parameters in these simple statistical models are typically supposed to represent the latent population-level values? 

* 'The addition of these **crossed** random intercepts of participants and items would begin to address the challenge posed by @clark1973 in our case study above.' 
  * I think the case study may have been removed? I couldn't find another reference to @clark1973

* 'When we had a simple OLS model above, we had only two parameters to fit ($\beta_0$ and $\beta_1$) but now we have those two plus two more, representing the standard deviations of the individual participant intercepts and slopes.'
  * plus 2x the number of participants? we also have to fit all of the individual intercepts and slopes, not just the standard deviations of the error. so if we have 10 participants, this is 2 + 2 + 10 + 10 parameters? 

* 'If you are manipulating a variable, include it in your model. If you are manipulating two, include them both and their interaction.'
  * We never introduce interaction terms before here, as far as I can tell. Maybe that's worth adding a paragraph in the basic OLS section?

* I thought using $\delta_t$ to denote a random intercept in the 'worked example' section was confusing since it was previously used for random slopes. I replaced it with $\gamma_t$, which I think is clear if you're thinking of all the indices as distinct strings. If we want to be extra careful, we could do $\gamma^{subj}_i + \gamma^{item}_t$ to represent the two classes of gammas, but that seemed like notational overkill.

* I might introduce lmer syntax in a little code box in the linear mixed effects models section to parallel the boxes for `lm` and `glm`.

* "7.3 Accommodating clustering in our models" is a stub despite being labeled as a 'major' section and I think it is probably supposed to be an introductory subsection of what is currently 7.4, i.e. 7.4.1?

* We're centering `age` in the example, allowing us to interpret the condition effect at the average age, but we don't currently discuss the difference between a simple effect and a main effect -- we're dummy-coding condition rather than effect-coding, so the age effect needs to be interpreted as a simple effect but the condition effect needs to be interpreted as a main effect. Maybe we can either highlight this and provide advice about interpretation (as an accident report?) or just center both variables to simplify?

**Comment by mcfrank** [comment]
thanks Robert, great comments! tried to address all of these in the revision.
