### ISSUE TITLE
Figure and question rendering in meta chapter (16) 

### ISSUE THREAD

**Issue by mayamathur** [langcog/experimentology#136]
1.) Some figures are rendering in the margins (despite the fact that most render in the body). E.g., figures 16.2 and 16.3.

2.) For figures that do render in the body, sometimes their legends are far away (e.g., 16.1).

3.) The discussion questions box is designed to have questions 1A, 1B, and 1C. This is rendering, however, as 1 (A), 2 (B), and 3 (C)

**Comment by mikabr** [comment]
1) You can toggle whether a figure is in the body or margin with the knitr chunk option `fig.margin=TRUE` or `fig.margin=FALSE` (default is `FALSE`).

2) The caption for 16.1 looks to me like it's right by the figure, can you please clarify what you mean?

3) Fixed now.

**Comment by mayamathur** [comment]
Thanks Mika! Tagging @ColesNicholas who had raised #1. With #2, I might have been rendering an old version since it looks fine now.
