### ISSUE TITLE
sidenote numbering is weird

### ISSUE THREAD

**Issue by TomHardwicke** [langcog/experimentology#140]
There's something weird happening with the sidenote numbering, not sequential and lots of ones e.g., screenshot below from the [replication chapter](https://experimentology.io/3-replication) 

<img width="415" alt="Screenshot 2023-06-13 at 17 09 18" src="https://github.com/langcog/experimentology/assets/5615147/7e60bc75-5872-4906-aa80-88716cfe56c5">

**Comment by mikabr** [comment]
removed the pdf label because this is web-specific issue

**Comment by mikabr** [comment]
fixed by quarto version
