### ISSUE TITLE
comments on chapter 4 - ethics

### ISSUE THREAD

**Issue by TomHardwicke** [langcog/experimentology#144]
I'm working through the book sequentially and these are my comments on chapter 4. I've also made some direct edits to the text for more minor things and writing adjustments (see [pull request](https://github.com/langcog/experimentology/pull/143)).

- when defining Beneficence we say "The second is to maximize potential benefits" — do we mean benefits specifically to the participants (rather than generally, e.g., to society)?

- "Further, Milgram’s study may have induced unnecessary harm by failing to screen participants for existing mental health issues before beginning the session." <- aren't we missing the more obvious point that the task appears to have actually been harmful to the participants?

- "Was the harm done in Milgram’s experiment justifiable given that it informed our understanding of obedience and conformity? We can’t say for sure" <- surprising answer! I would've said no it definitely was not, because of the ethical violations we've just outlined (autonomy, harm).

- "Additionally, shock administration never exceeded 150 volts (compared to 450 volts in the original study), and experimenters debriefed participants extensively following the end of the session. One year later," <- perhaps add a sidenote here with the results of this study, I'm intrigued!

- "A virtue is a trait, disposition, or quality that is thought to be a moral foundation" - the definition seems a bit tautological... how about 'reaches a high moral standard'?

- "Virtue ethics suggests that people can learn to be virtuous by observing those actions in others they admire (Morris and Morris 2016)."  <- is that an empirical claim or a theoretical claim? Perhaps we should say "Virtue ethicists suggest..."?

- "For example, there’s no reason to publish a result if you believe it is uninformative because of a small sample or a confound in the experimental design. You also aren’t committing an ethical violation if you decide to quit your job in research and so you don’t publish a study from your dissertation." <- actually can't all of these things lead to publication bias if the decision to publish is affected by the results? e.g., I imagine if the results are negative its easier to post-hoc rationalise its not worth publishing because of a confound or whatever, but if the results are positive, you're more likely to try and get it published. Also for dissertation studies, your supervisor might be more likely to encourage you to write it up as a paper if the result is positive. So perhaps our recommendation should be more along the lines so (1) decide if you are doing serious research that might be published; (2) if yes, then do your best to design an informative study; (3) try to make publication decisions before you've seen the results.

- "self-plagiarism within the text of journal articles" <- not sure what we mean by within the text - do we mean using the same text in more than one article?

**Comment by mcfrank** [comment]
great, responded to all. (my edit to the pub bias case is a little smaller than you suggested though).
