### ISSUE TITLE
comments on chapter 5 — estimation

### ISSUE THREAD

**Issue by TomHardwicke** [langcog/experimentology#146]
I'm working through the book sequentially and these are my comments on chapter 5. I've also made some direct edits to the text for more minor things and writing adjustments and issued a [pull request](https://github.com/langcog/experimentology/pull/145).

- "While this process now sounds like a quotidian experiment that might be done on a cooking reality show, it seems unremarkable only because it literally established the way science was done for the next century." <- not following this. Why would the fact that it had so much influence retrospectively make it seem unremarkable? Are we trying to say that despite its drabness it is actually quite remarkable given its subsequent influence?

- "Fisher recognized that this strategy was insufficient." — can we be explicit about why? (presumably because some potential confounds are unknown and even the ones we know about we can't necessarily control; randomisation addresses both).

- "Our causal theory is that the tea quality is affected by milk-tea ordering, so we’ll test that by rating tea quality both milk-first and tea-first." - this seems like a good opportunity to present a DAG to reinforce learning from Chapter 1

- "In practice, we might do a field trial in a cafe in which we approach patrons and ask them to participate in our experiment in exchange for a free cup of tea" <- perhaps add a sidenote saying something like "You might be thinking, is this sample representative of the population we want to generalize to? It's a good question! Sometimes it is necessary to trade-off representativeness and convenience. We address this issue in more detail in Chapter 10"

- "Right now we’re going to assume that our ratings are just simple numerical values and not worry about the fact that they come from a rating scale. This is what people often do, though it can cause problems in certain cases." <- this is a bit mysterious; I know we don't want to get into too much detail here, but can we be a little more explicit?

- Figure 5.2 - shouldn't the responses be integers?

- "denote the parameter we want to estimate" <- I don't think we've defined parameter anywhere yet, might be helpful?

- "First, we assume a model for how the data were generated" <- I think we can be clearer here. We introduced models in Chapter 3 (theory) in the sense of causal models; whereas here (I think) we are talking about statistical models. We should clarify the difference? And I expect it won't be clear to many readers what we mean by "how the data were generated".

- "the “model” is as simple..." <- unclear why we've put model in scare quotes

- "This variation can be summarized via a probability distribution, a mathematical entity that describes the properties of possible datasets" <- I think it would be helpful to be more explicit about *why* we want to do this.

- "The maximum likelihood estimation example above describes a common approach to estimating values" <- we should perhaps say "estimating parameters" to keep the terminology consistent?

- "In Bayesian estimation, we observe some data , consisting of the set of correct and incorrect responses in the experiment." <- the experiment doesn't involve correct/incorrect responses does it? Participants provide quality ratings.

- "We can do this via Bayesian estimation of [theta hat]" <- should that be theta?

- "Speaking informally, “likelihood” is just a synonym for probability, but this is a technical meaning for the term, which can get a bit confusing." <- do we mean there is a more technical definition that is different to the informal interpretation? 'this' is confusing here I think.

- "a bunch of low accuracy observations" <- what is a low accuracy observation?

- "we are biased downward in our posterior mean" <- its confusing to use the term bias here right? Because elsewhere in the book when we say bias we mean in the sense of a systematic deviation from truth.

- "Priors aren’t usually as strong as the one shown above. Figure [5.7] shows how the picture shifts when we have a weaker prior." <- I don't think we've outlined what we mean by 'strong' (more concentrated?) and 'weak' (more diffuse?) priors.

- Fig 5.6, 5.7, and 5.8, are all variations of the same situation, so I think we can make the captions clearer and more comparative (and the caption for 5.7 is wrong?). So Fig. 5.6 could be "Bayesian inference about tea ratings with a strong prior on low values". Fig. 5.7 could be "Bayesian inference about tea ratings with a weak prior". And Fig. 5.8 could be "Bayesian inference about tea ratings with a a strong prior on low values and more data".

- "5.2.1 Estimating the treatment effect" <- perhaps use "intervention effect" to be consistent with previous terminology

- "a single parameter (the mean in just the milk-first group) " <- in brackets is the sample estimate not the parameter. Change to "mean for people who add milk first"?

- "To estimate the treatment effect, we are positing a model in which the milk-first ratings are normally distributed with mean thetaM = thetaT + Beta  and with standard deviation ." <- I think its easy to get lost here, there's little build up to what I think is quite a complicated concept — probably unclear to a reader why are we are specifying the model like that / what it means

- "As you’d probably expect, this estimate BetaHat turns out to be simply the difference in sample means ThetaM - ThetaT <- we have not yet mentioned BetaHat, only Beta, so this is confusing. And shouldn't these theta's have hats if they are sample means?

- " If we have no prior beliefs at all, then we could specify a flat prior" <- we use a proportionality symbol in the equation here which I imagine many readers will be unfamiliar with — add an explanatory sidenote?

- "normal prior" <- perhaps be clear we mean normal distribution

- "We’re dropping the hats here because we’re now working with a whole bunch of estimates, so everything would have a hat!" <- what's wrong with a whole bunch of hats? Danger is someone misses the side note and gets confused. We also start using hats again shortly after in the sentence "We previously said that..."

- "In this scenario, even if tea led to the same 1-point absolute change in feelings of excitement" >- not sure why we start talking about excitement here, the DV is taste ratings? Also see "1-point change in excitement levels".

- "These ideas are simple but they lay the foundations for drawing inferences, where we move from estimates within a particular sample to inferences about the population." <- these is a bit confusing because we've already been talking about estimating population parameters in this chapter. And not sure what we mean by estimates within a particular sample, if the goal of the estimate is a population parameter 

- we say in a few places that the chapter will contrast frequentist and bayesian approaches; however, (1) we don't make clear that MLE is a frequentist approach; (2) we could be a bit more explicit about the high-level differences between these approaches. I also imagine a reader will be wondering we've introduced two approaches and which one they should use — so some direction on that might be helpful.

- "Psychology as a field has often been criticized for focusing too much on inference and too little on estimation" <- I'm finding this inference vs estimation dichotomy a bit odd — when we estimate a pop parameter from a sample estimate, we are making an inference. The relevant dichotomy for the quoted sentence is hypothesis testing vs estimation isn't it?

**Comment by mcfrank** [comment]
great comments, addressed these.
