### ISSUE TITLE
Some references in reference section don't show author name

### ISSUE THREAD

**Issue by TomHardwicke** [langcog/experimentology#149]
Here are two examples. I've checked the bibtex entires for these two and can't see what the problem is.

In chapter 5:
![Screenshot 2023-06-14 at 16 25 16](https://github.com/langcog/experimentology/assets/5615147/ef21a4df-520b-454a-ad0c-17f8121fb707)

In chapter 6:
![Screenshot 2023-06-15 at 13 37 54](https://github.com/langcog/experimentology/assets/5615147/489b48ac-7438-4276-bc8f-115fcec84a69)

**Comment by mcfrank** [comment]
that's an "ibid" from the tufte ref style... but it looks like it's happening across chapters, which isn't great.

**Comment by mikabr** [comment]
fixed by quarto version
