### ISSUE TITLE
Side note overlapping with main text

### ISSUE THREAD

**Issue by TomHardwicke** [langcog/experimentology#156]
In Chapter 10 we have a sidebar note overlapping with the main text. Tested in Safari and Chrome browsers, occurs both.

<img width="1091" alt="Screenshot 2023-06-17 at 15 54 52" src="https://github.com/langcog/experimentology/assets/5615147/e83f4a34-ffad-4d71-9706-69de19a3a89d">

**Comment by mikabr** [comment]
specifiicaly, the issue appears to be sidenotes being at the wrong position when they're next to a list

**Comment by mikabr** [comment]
fixed by quarto version
