### ISSUE TITLE
Comments of Chapter 10 — Sampling

### ISSUE THREAD

**Issue by TomHardwicke** [langcog/experimentology#158]
I'm working through the book sequentially and these are my comments on chapter 10. I've also made some direct edits to the text for more minor things and writing adjustments and issued a [pull request](https://github.com/langcog/experimentology/pull/157).

- "Imagine for a second what a non-generic version of one of these titles might look like: “Reading one particular selection of fonzy for fifteen minutes in the lab improved 36 college students’ smoodling scores on a questionnaire.” We wouldn’t let the authors get away with a fully general version of their claim: “Doing [any] fonzy improves smoodling [for anyone].” That’s just a bad generalization from the evidence we actually have." <- it's a bit unclear from this whether we consider the non-generic version to be good or bad...

- Figure 10.1 - in this figure, and I think pretty much throughout, we don't label our error bars. I know its to super important given the more generic points we're making, but perhaps we should demonstrate good practice

- "On the other hand, it’s more complicated to jump from a statistical generalization about average ability to a richer claim, like “as humans evolved, they lost olfactory ability and gained visual ability.” " <- This point on evolutionary claims seems tangential to the main point we've been trying to get across in this box, maybe cut?

- "what if they aren’t in the phone book" <- what the hell is a 'phone book'? I'm kidding. But genuinely — will our readers know this is?

- Figure 10.3 - labels pretty small, difficult to see the means and IDs (red)

- "So no estimate can be generalized to the object of study" <- that's too strong I think — its a matter of degree isn't it?

- "Should we throw up our hands and resign ourselves to an ungeneralizable “science” of sample-specific anecdotes?" <- perhaps cite Yarkoni's generalizability crisis paper in this section?

- "experimental effects" <- causal effects?

- Figure 10.4 caption needs to explain what different colours represent I think

- "If you have a random sample (top)" <- the graph says "representative" rather than "random"

- "This kind of theory sounds like a useful place to start, but there are also plenty of counter-examples in the literature" <- they are counter examples in the sense of finding variability in 'lower level' functions rather than finding 

- "As we learned in Chapter [3](https://experimentology.io/3-replication), continuing to collect data until you observe a p < .05 in an inferential test is a good way to get a false positive." <- I don't think we address it in much detail at all

- "classic power analysis" <- this seems to imply there's something different about the technique itself, but we're just talking about different types of justification. Should we say e.g., "most common power analysis justification" ?

- "General expectations about an effect of interest" <- I think this is the place to address smallest effect size of interest and we should remove it from Table 10.1 above — because its not a different method, its a specific aspect of power analysis.

- "A strong meta-analysis will have not only a precise effect size estimate but also some diagnostics detecting and correcting potential publication bias in the literature " <- I think we should be more cautious here — publication bias detection is not perfect and we have good reason to think most literatures are compromised by it in some way.

- pilot testing "Do not do this." <- that's perhaps a bit strong. I think there are principle (Bayesian?) methods for sample size planning that incorporate the uncertainty in the effect size estimate derived from a pilot study.

- "you can accept and reject the null, you may need to consider Bayesian approaches" <- is it fair to say that the Bayesian approach does not involving accepting or rejecting hypotheses at all, it involves quantifying the relative evidence for them?

- "Instead of trying to intuit how big your target effect is, you instead choose a level below which you might not be interested in detecting the effect." <- clarify that this can be based on theory (what is predicted, applied issues (what would matter), or resource issues (what's the smallest we can afford to power for)?

- weird formatting issue, line spacing is different in these two paragraphs, unclear why
<img width="814" alt="Screenshot 2023-06-17 at 16 04 09" src="https://github.com/langcog/experimentology/assets/5615147/c942dfe8-9895-433f-82ed-bc1b1f6fbf84">

- perhaps include Yarkoni's generalisability crisis piece in the further readings section (I don't feel strongly about it though)

**Comment by mcfrank** [comment]
great - did tom's comments, will look at Maya's next.
