### ISSUE TITLE
remove appendices A-D from PDF

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#162]
<img width="693" alt="Screenshot 2023-06-20 at 9 33 50 AM" src="https://github.com/langcog/experimentology/assets/1158807/20660850-0469-4679-b79d-529ec88bda05">

**Comment by mikabr** [comment]
should the appendices actually be in the print book at all?

**Comment by mcfrank** [comment]
good question. yes, I think that's right. let's take A-D out, but keep in the instructor guide. I will annotate the preface to note this. how do we get them not to render into the PDF?

**Comment by mcfrank** [comment]
also how do we get their references not to fail if we leave them out?

**Comment by mikabr** [comment]
instructor's guide is now appendix A, all other appendices have placeholders in the pdf
