### ISSUE TITLE
do we want a box around every page? 

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#164]
RN there is a box around each page of the pdf, not sure if we want this.

**Comment by mikabr** [comment]
The box is just for reference, it demarcates the printable area (the page itself is 8.5x11 but it's being printed in 8x10). You can toggle whether the frame appears in `preamble.tex` by removing the `frame` option from `\usepackage[frame,letter,center,noinfo]{crop}`.

**Comment by mcfrank** [comment]
great, turned off the box. :)
