### ISSUE TITLE
ensure code in boxes doesn't overflow

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#165]
<img width="809" alt="Screenshot 2023-06-20 at 9 44 20 AM" src="https://github.com/langcog/experimentology/assets/1158807/aa064f7a-d2b3-4ccb-ab32-d038bf0bfaa1">

**Comment by mcfrank** [comment]
how do we want to deal with this? we could remove code boxes from the PDF?

**Comment by mikabr** [comment]
I'm not sure, removing code boxes from the print book seems reasonable, though I've seen many a printed textbook with code in it

**Comment by mcfrank** [comment]
I think it would be reasonable to include the code. We can make sure that all code snippets are less than 80 chars wide, and maybe we can decrease font size so that 80 chars fit in the boxes? I think that won't be too small, rn the code font is big... does that sound good?

**Comment by mikabr** [comment]
The boxes are now fullwidth which largely solved the issue, when lines of code are still too long they need to just be broken up in the source code.
