### ISSUE TITLE
how do we control figure sizing?

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#166]
`out.width` and `fig.width` in chunk options don't work. but sometimes we want figures to be smaller so that their font sizes etc. show up a bit more nicely.

**Comment by mcfrank** [comment]
example, I think this should be smaller. 

<img width="424" alt="Screenshot 2023-06-20 at 1 12 51 PM" src="https://github.com/langcog/experimentology/assets/1158807/0fd517dd-adb4-4c93-849d-e85f461a6fef">

**Comment by mikabr** [comment]
I can't find this figure, was it replaced or something?

**Comment by mcfrank** [comment]
i see it in the pdf and on the web, but maybe it wasn't pushed before?

**Comment by mikabr** [comment]
`fig.` and `out.` chunk options should now work
