### ISSUE TITLE
tables too wide in PDF

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#169]
<img width="1042" alt="Screenshot 2023-06-21 at 9 50 28 AM" src="https://github.com/langcog/experimentology/assets/1158807/485a9955-9ca4-4b20-9dfa-2419ee53b3f5">

(looks good on the web)

**Comment by mcfrank** [comment]
note that this example is actually a table*, and this environment seems to be misbehaving. 

also, see the reference in text to table 6.4.1, even though the caption correctly says 6.3.

**Comment by mikabr** [comment]
It looks like the text needs to wrap for the table to fit and that's not enabled/working. Is that what you mean by the environment misbehaving?

**Comment by mcfrank** [comment]
yeah, I forgot you can just make latex tables that go off the page arbitrarily...
