### ISSUE TITLE
float clustering / rendering problems

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#170]
many floats render off page / get bunched up when there are a lot of captions and sidenotes. I am guessing the best way to deal with this is to set some tex penalties correctly to let sidenotes slide above their intended location or to the next page if they don't, but to make it very bad for them to be rendered off the print area. 

if we're messing with these penalties, we could set it to be worse for captions to move away from tables and figures, and better for sidenotes and margin figures to move away from anchor locations. 

<img width="943" alt="Screenshot 2023-06-21 at 9 52 47 AM" src="https://github.com/langcog/experimentology/assets/1158807/8c975f9f-f4ec-43a2-9f78-5d7302c4f538">

**Comment by mcfrank** [comment]
seems to me that none of this is done very automatically by default in the tufte-latex package. instead they seem to think you should set all of it by hand when you're at the end of the editing process: https://groups.google.com/g/tufte-latex/c/7cqVud-iQkg

**Comment by mikabr** [comment]
doing this manually at the end was my plan

**Comment by mikabr** [comment]
this is now largely solved by the `marginfix` latex package
