### ISSUE TITLE
idea: full-width on boxes

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#172]
ok, here's one crazy idea: since boxes can't have sidenotes, what if we made them full-width rather than paragraph-width. right now it's somewhat unattractive often when we get very skinny box text across many pages with no sidenotes. the more I think about this the more I like it. (but maybe it will look lame). 

as a side note, this would fix #165.

**Comment by mikabr** [comment]
it might look weird but the current setup looks weird too -- let's try it

**Comment by mcfrank** [comment]
cool!

**Comment by mikabr** [comment]
boxes are now all full-width except for learning goals boxes which are body-width because their content is generally quite narrow
