### ISSUE TITLE
Comments on Chapter 17 — Conclusions

### ISSUE THREAD

**Issue by TomHardwicke** [langcog/experimentology#183]
I'm working through the book sequentially and these are my comments on chapter 17. I've also made some direct edits to the text for more minor things and writing adjustments and issued a [pull request](https://github.com/langcog/experimentology/pull/182).

- the "summarising our approach" section is a bit of a grab bag of things. I wonder if a better structure might be to refer back to the four themes we mentioned in Chapter 0. 

- now I've reached the end of the book - I thought we could've done more to highlight the four themes throughout the book. We mentioned them of course, but they don't stand out particularly. I don't think it's a major issue, but highlighting them would provide a little structure and fortify these core principles/goals. Perhaps when we use one of the theme words it could have a highlighted background or we could flag in each chapter intro which themes will come up (or in chapter outros).

**Comment by mcfrank** [comment]
highlighted the themes throughout!
