### ISSUE TITLE
research metadata

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#186]
we need to:
- [x] add ORCIDs for authors
- [x] add DOI (maybe MIT press DOI?)
- [x] add CRediT taxonomy (perhaps for each chapter)

**Comment by mikabr** [comment]
here's the quarto schema for authors:
https://quarto.org/docs/journals/authors.html#author-schema
it explicitly supports both ORCIDs and CRediT

DOI is specific in book options:
https://quarto.org/docs/reference/projects/books.html#section

**Comment by mcfrank** [comment]
info is in wiki to be ported to meta-data
