### ISSUE TITLE
fix ch1 prison experiment box

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#188]
need to flesh out the accident report

**Comment by mcfrank** [comment]
@TomHardwicke @ColesNicholas I just closed this but if you wanted to review that would be great... text is in Ch1.

**Comment by TomHardwicke** [comment]
thanks @mcfrank — am I looking for an accident report in Chapter 1? I can't see one on the live page

**Comment by mcfrank** [comment]
we're not rerendering everything yet, but text is in the source at
https://github.com/langcog/experimentology/blob/18e1aa600b3b659ee6dc68c1a09a67a53aa7423e/001-experiments.qmd#L169

**Comment by TomHardwicke** [comment]
gotcha. Looks good to me. Minor suggestion, avoid double use of cruel in: "the cruelty of the participants acting as guards, who apparently engaged in a variety of cruel and dehumanizing behaviors towards the simulated prisoner"

**Comment by mcfrank** [comment]
Thanks!

Mike

**Comment by ColesNicholas** [comment]
Looks great, Mike!
