### ISSUE TITLE
add ORCIDs 

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#198]
we should get ORCIDs for each contributor and add them. mine is https://orcid.org/0000-0002-7551-4378 - @hawkrobe @rondeline @mikabr @mayamathur @juliecachia @TomHardwicke @ColesNicholas can you respond to this thread with yours? (if you don't have one you should get one!!)

**Comment by TomHardwicke** [comment]
https://orcid.org/0000-0001-9485-4952
________________________________
From: Michael Frank ***@***.***>
Sent: Friday, September 22, 2023 9:05:27 AM
To: langcog/experimentology ***@***.***>
Cc: Tom Hardwicke ***@***.***>; Mention ***@***.***>
Subject: [langcog/experimentology] add ORCIDs (Issue #198)


we should get ORCIDs for each contributor and add them. mine is https://orcid.org/0000-0002-7551-4378 - @hawkrobe<https://github.com/hawkrobe> @rondeline<https://github.com/rondeline> @mikabr<https://github.com/mikabr> @mayamathur<https://github.com/mayamathur> @juliecachia<https://github.com/juliecachia> @TomHardwicke<https://github.com/TomHardwicke> @ColesNicholas<https://github.com/ColesNicholas> can you respond to this thread with yours? (if you don't have one you should get one!!)

**Comment by ColesNicholas** [comment]
https://orcid.org/0000-0001-8583-5610

**Comment by juliecachia** [comment]
https://orcid.org/0000-0001-9584-457X
________________________________

**Comment by rondeline** [comment]
https://orcid.org/0000-0002-2690-1603

Rondeline Williams, MA (she/her)
PhD Candidate
Ford Fellow
Department of Psychology
Stanford University
________________________________

**Comment by mikabr** [comment]
https://orcid.org/0000-0001-9039-3220
