### ISSUE TITLE
Connect GH repo to Zenodo for DOI

### ISSUE THREAD

**Issue by zchandler** [langcog/experimentology#213]
For important works like this one, we should connect the Github repository to Zenodo for long term preservation, and to get a DOI for Experimentology:

https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content
https://www.lib.uiowa.edu/data/files/2022/10/Share_and_Preserve_Your_Code_20220728.pdf

At best, you would do this for all tagged releases (i.e. v.2, etc.)

THEN, you can add that DOI back into a .CFF file in your Github repo top level:
https://citation-file-format.github.io/

That way, more people will know how to cite you correctly, and you will show up in the PIDgraph bcs you will have a DOI.

**Comment by mcfrank** [comment]
thanks! we actually have a DOI from MIT press for the official pub, but it's hidden now because the link won't resolve until the project is published...
