### ISSUE TITLE
Linearity discussion in 7.1.4

### ISSUE THREAD

**Issue by poldrack** [langcog/experimentology#214]
Section 7.1.4 states the following:

```
The predictor relationships being modeled must be linear. In our comparison of Alice’s and Bob’s expected outcomes based on their 1-year age difference, we were able to interpret the coefficient as the average difference in when comparing participants who differ by 1 year of age, regardless of whether those ages are 20 vs. 21 or 50 vs. 51. But that’s not always true: plenty of things vary non-linearly with age – for example, imagine growth in height over age! Linear regression will give bad answers in such cases
```

I'm not sure that this is the right way to frame it.  While it is true that the regressors in the linear model enter the model in a linear fashion, there is no reason that one couldn't enter nonlinear transformations of those variables into the model as regressors, thus modeling a nonlinear relationship.  As an example, it's easy to model highly nonlinear relationships between X and Y by using a polynomial expansion of X.    And in the example you use, I don't see any reason that you couldn't include age**2 as a regressor to model a nonlinear relationship.

**Comment by mcfrank** [comment]
thanks, modified text!
