### ISSUE TITLE
problems in models 7.4.2 example

### ISSUE THREAD

**Issue by lbluefishl** [langcog/experimentology#229]
I believe I found a few discrepancies in this section.

First, the model uses delta_t, but later the explanation uses gamma_t. 

Second, I believe the labels may have been put in the wrong place on the table. I'm very new to learning these models, so I may be wrong. 

Specifically, the text mentions:
"The intercept (control condition estimate) ... corresponds to a probability of 0.69... that estimate makes sense: 0.69 seems close to the average for the control condition"
However, I believe the value 0.69 reflects the average for the experimental condition, not the control. 

Similarly, it says,
"The key experimental condition estimate is -2.26... which corresponds to a probability of 0.19... this estimate corresponds to the average value for the experimental condition."
I believe that 0.19 corresponds to the control condition, not the experimental. 

I performed the same analysis in R using the code provided. My coefficient for conditionControl was -2.26. Which should suggest that being in the control lowers the probability of success on the trial, which makes sense and follows the data. But the table 7.2 puts -2.26 coefficient for the experimental condition.

**Comment by mcfrank** [comment]
Thanks so much for catching this!
