### ISSUE TITLE
New GitHub Authentication

### ISSUE THREAD

**Issue by benpry** [langcog/experimentology#23]
Over the summer, GitHub changed the way you authenticate from the command line. Instead of entering your password, you need to create a personal access token. Should the git tutorial chapter contain instructions about how to use the new authentication system? In particular, it might be nice to cover:
- Creating a personal access token
- Configuring the credential helper to store a password
- Logging in with the personal access token

**Comment by JYAC** [comment]
Thanks @benpry! The new paragraph I added on this should show up the next time the book is rendered :)
