### ISSUE TITLE
Adding a little more context.

### ISSUE THREAD

**Issue by uyjco0** [langcog/experimentology#233]
In the chapter 1, "Experiments", under the section 1.1, "Observational studies don’t reveal causality", it is stated the following:

"The 'causal revolution' in the social sciences has been fueled by the development of statistical methods for reasoning about causal relationships from observational datasets. As interesting as these methods are, however, they are only applicable in certain specific circumstances".

I'm really interested in knowing more about what these "specific circumstances" are, but given my knowledge, I don't know how to search on that topic. The references at the end of the chapter don't help me, because I don't understand which of them has the material that covers that topic. 

Could you suggest any article that speaks specifically about that topic to an advanced undergraduate in social sciences?

Thanks!

**Comment by mcfrank** [comment]
Hi there,

Take a look at this reference. It's a free textbook on causal inference:
https://theeffectbook.net/. It's really good.

Mike

**Comment by uyjco0** [comment]
Wow! Thanks a lot Michael!
