### ISSUE TITLE
appendix styling

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#3]
we should probably figure out if appendices are just chapters or if there is some special way they are accessible / special numbering. :)

**Comment by JYAC** [comment]
Yes - I was going to bring up the same point! I feel like some of the appendices are more conducive to chapter-format than some of the others: for instance, the "Github tutorial" and "Instructor's guide" would be nice in chapter-format, but the "R Markdown tutorial", "Tidyverse tutorial" and "ggplot tutorial" all seem best suited for direct interaction within R Markdown, so I wonder if those three could be links to RMarkdown code kind of like [this one](https://raw.githubusercontent.com/mcfrank/openscience_tutorial/master/rmarkdown_handout.Rmd) that we have for Psych 251?

**Comment by mcfrank** [comment]
interesting... I didn't love how the tutorial appendices worked having taught from them.

I think we should:
1.  try to get them to be off of the TOC at the top
2. try to get them to be lettered rather than numbered
3. be chapter-ish with numbered sections but with exercises interspersed

**Comment by mikabr** [comment]
I'm not sure what you mean?

**Comment by mcfrank** [comment]
sorry, I am trying to think through how we want to present things like the ggplot tutorial as an appendix.

take a look at it right now. it's pretty nonsensical - the code doesn't show (easy to fix, but still). it was written to be navigated in code with the chunks run in sequence, and with the exercises filled in. 

in an ideal world, it would be presented with interactive code chunk windows where you could run things inline. not sure if we can do that, but it would be awesome. if not, we have to think about what the pros/cons of presenting a tutorial like this in a static format are...

**Comment by mikabr** [comment]
oh I see. we should be able to do that by setting it up as a `learnr` tutorial! not sure how seamlessly that would integrate with bookdown, will investigate.

**Comment by mcfrank** [comment]
Oh that looks amazing! yes, that would be a great way to set these up.
