### ISSUE TITLE
citation style issue with multi-year cites

### ISSUE THREAD

**Issue by TomHardwicke** [langcog/experimentology#34]
In prereg chapter we cite the 2014 translation of an article originally published by de Groot in 1956. Currently the in-text citation is appearing as "Groot (2014)" and I think it should appear as "de Groot (1956/2014)". Does anyone know how to fix it?

Here's the full reference:
de Groot, A. D. (1956/2014). The meaning of “significance” for different types of research (E.-J. Wagenmakers, D. Borsboom, J. Verhagen, R. A. Kievit, M. Bakker, A. O. J. Cramer, D. Matzke, D. Mellenbergh, & H. L. J. van der Maas, Trans.). Acta Psychologica, 148, 188–194. https://doi.org/10.1016/j.actpsy.2014.02.001

**Comment by mikabr** [comment]
actually needs to be `{de Groot}, A. D.`
