### ISSUE TITLE
feedback on data collection chapter

### ISSUE THREAD

**Issue by ColesNicholas** [langcog/experimentology#35]
**We need to develop a broad narrative for the section (and how it fits in w/ the rest of the book)**

Not sure what this will be. One narrative I’ve used in my previous methods course is that experiments can range from highly informative to utterly useless to completely misleading. And things like measurement, sampling, study design, statistical methods, and research practices help determine where a research endeavor lands. This chapter talks a bit about data collection research practices that help determine how useful the study will be. As is clear as the chapter progresses, these research practices intersect with things like measurement and study design. Sometimes strong research practices help us learn that our measures are confusing, that our manipulations are ineffective, that our paradigms are distracting, etc.

**Potential accident report: the perils of not piloting**
I think pilot study is a perfect place to put an accident report. I’m sure there is a very long list we could pull from.

E.g., in my first semester of grad school, I helped coordinate an expensive data collection effort for an experiment developed shortly before I arrived. A few months later, I was informed that the program never actually recorded the primary outcome of interest. The project was a waste of hundreds of hours of RA, participant, and graduate student time—all because we did not pilot our data processing/analysis procedures.

**clarify scope of data integrity section**
Is the idea for this section to overview some *strategies* that people can use to check the integrity of the data?
This might include things like (a) adding attention check items; (b) measuring how long people are spending on pages / the entire study; and (c) funnel debriefings (even if done online).

**consider removing discussion of field studies**
This seems to be more of a methods vs. data collection issue.

**Comment by mcfrank** [comment]
thanks for this comment! 

re: narrative - I think my thought was "here are some basic tricks you can do to keep your study on track - you designed it well, have a good analysis plan, but don't undermine it via inattentive participants, bad data logging, etc. etc."

I really like the idea of doing an accident report on your grad school experience. (I did something similar FWIW). That would be great to add. 

strategies for data integrity - exactly! All of your ideas are fabulous. We especially need to talk about attention checks/manipulation checks/instructional manipulation checks and their uses and misuses (e.g., can introduce selection bias on participants or differential attrition across conditions). 

field methods, yes, let's cut.
