### ISSUE TITLE
Welch's vs. equal-variance t-test continuity

### ISSUE THREAD

**Issue by mayamathur** [langcog/experimentology#38]
The estimation chapter foreshadows *Welch's* t-test because it describes unequal variances. The Inference chapter generically refers to a t-test without making distinction. The Models chapter opens with the equal-variance t-test as a special case of OLS, which would become trickier if that chapter described Welch's t-test. Let's discuss how to handle this.

**Comment by mcfrank** [comment]
we're going to assume equal variances (footnote) in estimation - just to make things match with Moldes.

**Comment by mcfrank** [comment]
we use \sigma_{pooled} for effect size in Estimation, but in Inference we just assert a t-test and don't mention equal or unequal variances. maybe a footnote can sort this out?

**Comment by mayamathur** [comment]
@mayamathur is on it

**Comment by mcfrank** [comment]
@mayamathur should we close this?
