### ISSUE TITLE
Notation and vocab master lists?

### ISSUE THREAD

**Issue by mayamathur** [langcog/experimentology#40]
Should we have masters list of notation and vocabulary that has been introduced in each chapter, so that these can be synced across chapters at the end? I've been jotting down some of these within the chapters themselves, but a master list might be helpful.

**Comment by mcfrank** [comment]
This is maybe more like an index, at least for vocabulary? I think a search bar would do the trick for vocab (but not for notation). For notation, we only have three chapters with major notation so I'm not sure it's worth while. Closing this in favor of #42.
