### ISSUE TITLE
handle footnote/caption citations

### ISSUE THREAD

**Issue by hawkrobe** [langcog/experimentology#5]
when you cite something in a side-bar element, it adds a side-bar to the side-bar, which doesn't look great. can we get those citations to appear below the side-bar element that's citing them? 

<img width="573" alt="CleanShot 2021-08-30 at 01 40 20@2x" src="https://user-images.githubusercontent.com/5262024/131311756-6679cb8b-d2be-4628-8f4b-2ac6c72a6ed2.png">

<img width="1342" alt="CleanShot 2021-08-30 at 01 39 46@2x" src="https://user-images.githubusercontent.com/5262024/131311697-5824415c-f1bf-4a49-b8fe-8527b583c494.png">

**Comment by mcfrank** [comment]
I think this is supposed to be a feature of the tufte style, not a bug...

but it does make me wonder whether we want to try and hack the tufte style
to keep the marginalia but not the margin references, since @mmathur has
also noted that repeated or extensive citations don't look so nice.
