### ISSUE TITLE
dylan dependence

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#63]
The Dylan example is woven into chapters 2 and 9, but is no longer in chapter 1. We need to go through and adjust some of our figures and text...

@ColesNicholas

**Comment by ColesNicholas** [comment]
@mcfrank, how do you prefer to proceed here? Want me to take a crack at updated the Dylan example in Chapter 2?

I also skimmed Ch. 9 so I can start thinking about it as well--but the theory chapter is fresher on my mind.
