### ISSUE TITLE
include box on multicollinearity?

### ISSUE THREAD

**Issue by hawkrobe** [langcog/experimentology#78]
I don't believe we currently discuss the problem of correlated predictors anywhere? 

It could belong in the models chapter when first introducing multiple regression (maybe an 'accident report' if that's not stretching the concept too much). and then it could also be worth a mention in the measurement chapter where we discuss the pros and cons of measuring lots of things at once and throwing them all in as covariates?

**Comment by mcfrank** [comment]
having just revised the models chapter with your great feedback, I think I am leaning against this. multicollinearity is a specific statistical issue that is better treated by a stats book, and I worry that we are already too technical in the models chapter (see e.g. Tom's comment that this chapter is much denser than other content in the book).
