### ISSUE TITLE
ethical considerations box underused

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#79]
Right now we only have two ethical considerations boxes. We should either make more or let them drop entirely. What do you think @TomHardwicke @rondeline @ColesNicholas ? Would you be up for adding some ethics boxes in relevant locations, e.g. prereg (maybe about drug trial ethics), theory (who do we theorize about), writing?

**Comment by ColesNicholas** [comment]
@mcfrank 

Happy to brainstorm and work on an ethics box for theory.

We already cover cross-cultural generalizability issues in the previous chapter--but can certainly do so again here. Another idea is to talk about the ethics of _what we theorize about_. For example, Limited Energy Theory was used to justify gender-based inequity in education. People might reasonably argue about whether the reasoning was any less sound than other theories in the history of science--but it highlights that the things we theorize about have consequences.

**Comment by mcfrank** [comment]
Robert suggests IQ box in measurement chapter.

**Comment by mcfrank** [comment]
removed this and made them all accident reports. so it goes.
