### ISSUE TITLE
should we have memes?

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#8]
I think it would be fun to try and make memes for each chapter with the chapter take homes? if someone is feeling like procrastinating...

**Comment by mcfrank** [comment]
Like this: https://twitter.com/rlmcelreath/status/1434107690826010625?s=21

**Comment by mikabr** [comment]
into it! there's also a of stats-relevant xkcd comics

**Comment by mcfrank** [comment]
memed it.
